CREATE TABLE "PUBLIC"."CLIENT"( 
    "ID" INTEGER NOT NULL auto_increment, 
    "NAME" VARCHAR(255),      
    "CIF" VARCHAR(255), 
    "REP_NAME" VARCHAR(255), 
    "REP_SURNAME_1" VARCHAR(255),
    "REP_SURNAME_2" VARCHAR(255), 
    "DNI" VARCHAR(255), 
    "BANK_ACCOUNT" VARCHAR(255),
    "DATE_AGREEMENT_BEGIN" DATE, 
    "DATE_AGREEMENT_END" DATE, 
    "AGREEMENT_DURATION" INTEGER, 
    "AGREEMENT_TYPE" VARCHAR(255),    
    "STREET_TYPE" VARCHAR(255),
    "FISCAL_ADDRESS" VARCHAR(255), 
    "UNIT" VARCHAR(255),
    "PROVINCE" VARCHAR(255),
    "CITY" VARCHAR(255), 
    "COUNTRY" VARCHAR(255), 
    "POSTAL_CODE" INTEGER, 
    PRIMARY KEY ("ID")
);

CREATE TABLE "PUBLIC"."FARM"( 
    "ID" INTEGER NOT NULL auto_increment,
    "STREET_TYPE" VARCHAR(255),
    "ADDRESS" VARCHAR(255), 
    "UNIT" VARCHAR(255),
    "PROVINCE" VARCHAR(255),
    "CITY" VARCHAR(255), 
	"POSTAL_CODE" INTEGER, 
    "COUNTRY" VARCHAR(255), 
    "NUM_SANDACH" VARCHAR(255)     
    
        "CONTACT_NAME" VARCHAR(255), 
    "CONTACT_PHONE" INTEGER, 
    "CLIENT_ID_CLIENT_CODE" INTEGER,
    PRIMARY KEY ("ID"),
    FOREIGN KEY("CLIENT_ID_CLIENT_CODE") REFERENCES "PUBLIC"."CLIENT"("CLIENT_CODE")
);

CREATE TABLE "PUBLIC"."HYDROLYZER"( 
    "ID" INTEGER NOT NULL auto_increment, 
    "DATE_INI" DATE, 
    "MAX_WEIGTH" FLOAT, 
    "CLIENT_ID_CLIENT_CODE" INTEGER,
    PRIMARY KEY ("ID"),
    FOREIGN KEY("CLIENT_ID_CLIENT_CODE") REFERENCES "PUBLIC"."CLIENT"("CLIENT_CODE")
);

CREATE TABLE "PUBLIC"."INSTALLATION"( 
    "ID" INTEGER NOT NULL auto_increment, 
    "COLLECTED_WEIGTH" FLOAT, 
    "DELIVERY_DATE" DATE, 
    "INITIAL_WEIGTH" FLOAT, 
    "RETURN_DATE" DATE, 
    "SEAL_DATE" DATE,
    PRIMARY KEY ("ID")
);

CREATE TABLE "PUBLIC"."INSTALLATION_FARM"( 
    "INSTALLATION_ID" INTEGER NOT NULL,  
    "FARM_ID" INTEGER NOT NULL,
    PRIMARY KEY("INSTALLATION_ID", "FARM_ID"),
    FOREIGN KEY("FARM_ID") REFERENCES "PUBLIC"."FARM"("ID"),
    FOREIGN KEY("INSTALLATION_ID") REFERENCES "PUBLIC"."INSTALLATION"("ID")
);

CREATE TABLE "PUBLIC"."INSTALLATION_HYDROLYZER"( 
    "INSTALLATION_ID" INTEGER NOT NULL, 
    "HYDROLYZER_ID" INTEGER NOT NULL,
    PRIMARY KEY("INSTALLATION_ID", "HYDROLYZER_ID"),
    FOREIGN KEY("HYDROLYZER_ID") REFERENCES "PUBLIC"."HYDROLYZER"("ID"),
    FOREIGN KEY("INSTALLATION_ID") REFERENCES "PUBLIC"."INSTALLATION"("ID")
);