CREATE TABLE "PUBLIC"."CLIENT"( 
    "CLIENT_CODE" INTEGER NOT NULL, 
    "CC" VARCHAR(255), 
    "CIF" VARCHAR(255), 
    "DNI" VARCHAR(255), 
    "T" INTEGER, 
    "ADDRESS" VARCHAR(255), 
    "CITY" VARCHAR(255), 
    "COUNTRY" VARCHAR(255), 
    "DATE_FIN" DATE, 
    "DATE_INI" DATE, 
    "F_ADDRESS" VARCHAR(255), 
    "F_CITY" VARCHAR(255), 
    "F_COUNTRY" VARCHAR(255), 
    "F_POSTAL_CODE" INTEGER, 
    "F_PROVINCE" VARCHAR(255), 
    "NAME" VARCHAR(255), 
    "NUMC" INTEGER, 
    "POSTAL_CODE" INTEGER, 
    "PROVINCE" VARCHAR(255), 
    "REGA" VARCHAR(255), 
    "REPRESENTATIVE" VARCHAR(255), 
    "SURNAME" VARCHAR(255),
    PRIMARY KEY ("CLIENT_CODE")
);

CREATE TABLE "PUBLIC"."FARM"( 
    "ID" INTEGER NOT NULL, 
    "ADDRESS" VARCHAR(255), 
    "CITY" VARCHAR(255), 
    "CONTACT_NAME" VARCHAR(255), 
    "CONTACT_PHONE" INTEGER, 
    "COUNTRY" VARCHAR(255), 
    "NUM_SANDACH" VARCHAR(255), 
    "POSTAL_CODE" INTEGER, 
    "PREFIX" VARCHAR(255), 
    "PROVINCE" VARCHAR(255), 
    "CLIENT_ID_CLIENT_CODE" INTEGER,
    PRIMARY KEY ("ID"),
    FOREIGN KEY("CLIENT_ID_CLIENT_CODE") REFERENCES "PUBLIC"."CLIENT"("CLIENT_CODE")
);

CREATE TABLE "PUBLIC"."HYDROLYZER"( 
    "ID" INTEGER NOT NULL, 
    "DATE_INI" DATE, 
    "MAX_WEIGTH" FLOAT, 
    "CLIENT_ID_CLIENT_CODE" INTEGER,
    PRIMARY KEY ("ID"),
    FOREIGN KEY("CLIENT_ID_CLIENT_CODE") REFERENCES "PUBLIC"."CLIENT"("CLIENT_CODE")
);

CREATE TABLE "PUBLIC"."INSTALLATION"( 
    "ID" INTEGER NOT NULL, 
    "COLLECTED_WEIGTH" FLOAT, 
    "DELIVERY_DATE" DATE, 
    "INITIAL_WEIGTH" FLOAT, 
    "RETURN_DATE" DATE, 
    "SEAL_DATE" DATE,
    PRIMARY KEY ("ID")
);

CREATE TABLE "PUBLIC"."INSTALLATION_FARM"( 
    "INSTALLATION_ID" INTEGER NOT NULL, 
    "FARM_ID" INTEGER NOT NULL,
    PRIMARY KEY("INSTALLATION_ID", "FARM_ID"),
    FOREIGN KEY("FARM_ID") REFERENCES "PUBLIC"."FARM"("ID"),
    FOREIGN KEY("INSTALLATION_ID") REFERENCES "PUBLIC"."INSTALLATION"("ID")
);

CREATE TABLE "PUBLIC"."INSTALLATION_HYDROLYZER"( 
    "INSTALLATION_ID" INTEGER NOT NULL, 
    "HYDROLYZER_ID" INTEGER NOT NULL,
    PRIMARY KEY("INSTALLATION_ID", "HYDROLYZER_ID"),
    FOREIGN KEY("HYDROLYZER_ID") REFERENCES "PUBLIC"."HYDROLYZER"("ID"),
    FOREIGN KEY("INSTALLATION_ID") REFERENCES "PUBLIC"."INSTALLATION"("ID")
);