CREATE TABLE "PUBLIC"."CLIENT"( 
    "ID" INTEGER NOT NULL auto_increment, 
    "NAME" VARCHAR(255),      
    "CIF" VARCHAR(255), 
    "REP_NAME" VARCHAR(255), 
    "REP_SURNAME_1" VARCHAR(255),
    "REP_SURNAME_2" VARCHAR(255), 
    "DNI" VARCHAR(255), 
    "BANK_ACCOUNT" VARCHAR(255),
    "DATE_AGREEMENT_BEGIN" DATE, 
    "DATE_AGREEMENT_END" DATE, 
    "AGREEMENT_DURATION" INTEGER, 
    "AGREEMENT_TYPE" VARCHAR(255),    
    "STREET_TYPE" VARCHAR(255),
    "FISCAL_ADDRESS" VARCHAR(255), 
    "UNIT" VARCHAR(255),
    "PROVINCE" VARCHAR(255),
    "CITY" VARCHAR(255), 
    "COUNTRY" VARCHAR(255), 
    "POSTAL_CODE" INTEGER, 
    PRIMARY KEY ("ID")
);

CREATE TABLE "PUBLIC"."FARM"( 
    "ID" INTEGER NOT NULL auto_increment,
    "NAME" VARCHAR(255),
    "REGA" VARCHAR(255),
    "STREET_TYPE" VARCHAR(255),
    "ADDRESS" VARCHAR(255), 
    "UNIT" VARCHAR(255),
    "PROVINCE" VARCHAR(255),
    "CITY" VARCHAR(255), 
	"POSTAL_CODE" INTEGER, 
    "COUNTRY" VARCHAR(255), 
    "LATITUDE" FLOAT,
    "LONGITUDE" FLOAT,
    "NUM_SANDACH" VARCHAR(255),   
    "CLIENT_ID_CLIENT_ID" INTEGER,
    PRIMARY KEY ("ID"),
    FOREIGN KEY("CLIENT_ID") REFERENCES "PUBLIC"."CLIENT"("ID")
);

CREATE TABLE "PUBLIC"."HYDROLYZER"( 
    "ID" INTEGER NOT NULL auto_increment, 
    "SERIAL_CODE" VARCHAR(255),
    "DATE" DATE, 
    "MAX_WEIGHT" FLOAT, 
    "HYDRO_WEIGHT" FLOAT,
    "FARM_ID_FARM_ID" INTEGER,
    PRIMARY KEY ("ID"),
    FOREIGN KEY("FARM_ID") REFERENCES "PUBLIC"."FARM"("ID")
);

CREATE TABLE "PUBLIC"."INSTALLATION"( 
    "ID" INTEGER NOT NULL auto_increment, 
    "COLLECTED_WEIGHT" FLOAT, 
    "DELIVERY_DATE" DATE, 
    "COLLECTED_DATE" DATE,
    "FINISHED_DATE" DATE,
    "SEAL_DATE" DATE,
    "STATUS" VARCHAR(50),
    PRIMARY KEY ("ID"),
    FOREIGN KEY("CLIENT_ID") REFERENCES "PUBLIC"."CLIENT"("ID"),
    FOREIGN KEY("FARM_ID") REFERENCES "PUBLIC"."FARM"("ID"),
    FOREIGN KEY("HYDROLYZER_ID") REFERENCES "PUBLIC"."HYDROLYZER"("ID")    
);

CREATE TABLE "PUBLIC"."CONTACT"( 
    "ID" INTEGER NOT NULL auto_increment,  
    "NAME" VARCHAR(255) NOT NULL, 
    "SURNAME_1" VARCHAR(255),
    "SURNAME_2" VARCHAR(255), 
    "PHONE" VARCHAR(255),  
    "ACTIVE" BOOLEAN NOT NULL,
    PRIMARY KEY("ID")
);

CREATE TABLE "PUBLIC"."CONTACT_FARM"( 
    "CONTACT_ID" INTEGER NOT NULL, 
    "FARM_ID" INTEGER NOT NULL,
    PRIMARY KEY("CONTACT_ID", "FARM_ID"),
    FOREIGN KEY("FARM_ID") REFERENCES "PUBLIC"."FARM"("ID"),
    FOREIGN KEY("CONTACT_ID") REFERENCES "PUBLIC"."CONTACT"("ID")
);